spring:
  application:
    name: "challenge_foro_hub"
  datasource:
    url: "jdbc:mysql://localhost/challenge_foro"
    username: "root"
    password: "Sisiguaka8#1b36"
  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true
server:
  error:
    include-stacktrace: never
api:
  security:
    secret: 11jun1999